### ISSUE TITLE
Instantaneous swipe speed

### ISSUE THREAD

**Issue by CyberMageIL** [Kok3995/EMM#1]
All the current swipe speeds introduce extra hidden swipe points to bridge the gap between the user-defined swipe points.
What could be useful, at least for me, is the addition of an "Instantaneous" swipe speed setting, that doesn't add any extra swipe points or added timings behind the scenes, as those non-instant speeds and extra swipe points lead to less than accurate and/or inconsistent results... at least for my use case.

Otherwise, EMM is a well built and amazingly useful tool :)

**Comment by Kok3995** [comment]
Thanks for feedback. Those extra points is needed in any case to send to the system. You could think of them like a stream of events. Anyway, I've been working on a new version in the last year. It's mostly done, I only have the network infrastructure left. I'll open an beta soon. You can write script in the new version so having someone know how to code will help alot. Hope you can join

**Comment by CyberMageIL** [comment]
I see... with MEmu I usually write the macros manually (if it's doing long and complex work) and found that for the most accurate results just press & hold the initial point and then jump to the next point (& hold) works best when I need to scroll a page with as much accuracy as possible. Having the added extra points might not be an issue if no scrolling is involved.
But granted, I haven't had the chance to test how swiping works in other emulators' macros and have no idea if their system requires those extra points, so I'll refer to your judgement on the matter.
For now, since my swiping needs only requires 2 points per swipe, my workaround is just setting the 2nd point to a unique number close enough to the 1st point so that "Flick" will not add the extra points as the 2 points are so close.... then I just search the exported macro file for the unique number and replace it with my intended x,y coords.

If you're busy with the new version or if it is indeed a requirement for other emulators, I completely understand and you're welcome to close the issue request.
Looking forward to the new version, keep up the good work :)

**Comment by Kok3995** [comment]
woa you wrote it manually as in editing the script file? That's dedication right there. I'll close this issue then
